site_name: Unir CP2
site_description: Automatización de Infraestructura en Azure con Terraform y Ansible
repo_url: https://github.com/charlstown/unir-cp2
site_author: Carlos Grande

# Configuration
# Theme
theme:
  name: material
  #custom_dir: overrides
  static_templates:
    - 404.html
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.path # Path rendered on the upper side
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor in the table of contents.
    - navigation.tabs # Top-level sections are rendered in a menu layer below the header for viewports above
    - navigation.instant # Instant navigation is enabled by default
    - navigation.sections # top-level sections are rendered as groups in the sidebar for viewports above
    - navigation.footer
    - navigation.top # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again
    #- toc.integrate # Table of contents is always rendered as part of the navigation sidebar on the left.
    - search.suggest
    - search.highlight
    - content.code.copy # Codeblocks
    - content.tabs.link
    - navigation.indexes # Documents attached to sections
  language: es

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2-4  # Only show H2 and H4

# Plugins
plugins:
  - search
  - markdownextradata
  - awesome-pages
  - drawio
  - with-pdf:
      cover_subtitle: "Despliegue y configuración de infraestructura en Azure"

# css
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/pdf-custom.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - assets/javascripts/drawio-reload.js

# Copyright message
copyright: Copyright &copy; Unir CP2 - 2025

# Global variables
extra:
  links:
    self-host: 'url'
    learning-host: 'url'
