name: Publish StackEdit image to ACR

on:
  workflow_dispatch:  # Allows manual execution
    inputs:
      acr_name:
        description: "Azure Container Registry Name"
        required: true
        default: "acrweucp2dev"
      acr_username:
        description: "Azure Container Registry Username"
        required: true
        default: "acrweucp2dev"
      acr_password:
        description: "Azure Container Registry Password"
        required: true
        type: string
      image_name:
        description: "Container Image Name"
        required: true
        default: "stackedit"
      tag_name:
        description: "Tag Name"
        required: true
        default: "1.0.0"

env:
  ACR_NAME: ${{ github.event.inputs.acr_name }}
  IMAGE_NAME: ${{ github.event.inputs.image_name }}
  RELEASE_TAG: ${{ github.event.inputs.tag_name }}

jobs:
  publish-stackedit:
    runs-on: ubuntu-latest
    steps:
      
      # ✅ Checkout repository (not strictly needed, but keeps the workflow clean)
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Install Podman
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      # ✅ Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ github.event.inputs.acr_password }}" | podman login ${ACR_NAME}.azurecr.io -u ${ACR_NAME} --password-stdin    

      # ✅ Pull StackEdit image from Docker Hub
      - name: Pull StackEdit Image from Docker Hub
        run: |
          podman pull docker.io/benweet/stackedit-base:latest

      # ✅ Tag the image for ACR
      - name: Tag Image for ACR
        run: |
          podman tag docker.io/benweet/stackedit-base:latest ${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${RELEASE_TAG}

      # ✅ Push Image to ACR
      - name: Push Image to ACR
        run: |
          podman push ${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${RELEASE_TAG}
